name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup ADK
        run: |
          Invoke-WebRequest -O adksetup.exe https://download.microsoft.com/download/6/7/4/674ec7db-7c89-4f2b-8363-689055c2b430/adk/adksetup.exe
          Start-Process -Wait .\adksetup.exe -ArgumentList "/quiet /norestart /ceip off /features OptionId.DeploymentTools"
      
      - name: Setup WinPE Addons
        run: |
          Invoke-WebRequest -O adkwinpesetup.exe https://download.microsoft.com/download/5/2/5/525dcde0-c7b8-487a-894d-0952775a78c7/adkwinpeaddons/adkwinpesetup.exe
          Start-Process -Wait .\adkwinpesetup.exe -ArgumentList "/quiet /norestart /ceip off /features OptionId.WindowsPreinstallationEnvironment"
      
      - name: Test
        run: |
          dir $env:TEMP/ADK/
          #type $env:TEMP/ADK/*
          dir "C:\Program Files (x86)\Windows Kits\"
          dir "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\"
        
      - name: Setup the ENV
        run: cmd /c "C:\Program^ Files^ ^(x86^)\Windows^ Kits\10\Assessment^ and^ Deployment^ Kit\Deployment^ Tools\DandISetEnv.bat && cmd /c echo %PATH%" >> $GITHUB_ENV

      - name: Create the WinPE directory
        run: copype amd64 C:\WinPE_amd64
        
      - name: Create the WinPE directory
        run: MakeWinPEMedia /ISO C:\WinPE_amd64 C:\WinPE_amd64\WinPE_amd64.iso
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WinPE_amd64.iso
          path: C:\WinPE_amd64\WinPE_amd64.iso
